require 'octokit'

# Track 4 — Auto-PR Bot
# Creates a branch, commits a fix document, and opens a PR in the factory repo.
# Mirrors the pattern in factory/lib/utils/github_helper.rb (create_branch, commit, create_pull_request).
class AutoPr
  def initialize(config)
    @token        = config&.fetch('access_token', nil)
    @factory_repo = config&.fetch('factory_repo', nil)
    @client       = Octokit::Client.new(access_token: @token) if @token
  end

  # Raises a fix PR for the given finding.
  # Returns the PR URL string, or nil on error.
  def raise_pr(finding)
    return warn 'AutoPr: no GitHub token configured'    unless @client
    return warn 'AutoPr: no factory_repo configured'   unless @factory_repo
    return warn 'AutoPr: finding has no index_suggestion' unless finding[:index_suggestion]

    branch  = branch_name(finding)
    base_sha = master_sha

    # TODO: implement full branch + commit + PR flow
    # Step 1 — create branch
    #   @client.create_ref(@factory_repo, "refs/heads/#{branch}", base_sha)
    #
    # Step 2 — commit fix file
    #   file_path    = "db/performance_fixes/#{file_name(finding)}"
    #   file_content = fix_document(finding)
    #   blob_sha     = @client.create_blob(@factory_repo, Base64.encode64(file_content), 'base64')
    #   tree_sha     = @client.create_tree(@factory_repo,
    #                    [{ path: file_path, mode: '100644', type: 'blob', sha: blob_sha }],
    #                    base_tree: base_sha).sha
    #   commit_sha   = @client.create_commit(@factory_repo,
    #                    "perf: add index fix for #{finding[:collection]} [PerformanceIQ]",
    #                    tree_sha, base_sha).sha
    #   @client.update_ref(@factory_repo, "heads/#{branch}", commit_sha)
    #
    # Step 3 — open PR
    #   pr = @client.create_pull_request(@factory_repo, 'master', branch, pr_title(finding), pr_body(finding))
    #   pr.html_url

    nil
  end

  private

  def master_sha
    @client.ref(@factory_repo, 'heads/master').object.sha
  end

  def branch_name(finding)
    date = Time.now.strftime('%Y%m%d')
    slug = finding[:collection].to_s.gsub('_', '-')
    "perf-fix/#{slug}-index-#{date}"
  end

  def file_name(finding)
    date = Time.now.strftime('%Y%m%d')
    "#{date}_#{finding[:collection]}_index.md"
  end

  def pr_title(finding)
    avg_ms = finding[:avg_duration_ms].to_i
    "[PerformanceIQ] Fix #{avg_ms}ms avg query on #{finding[:collection]}"
  end

  def pr_body(finding)
    avg_ms = finding[:avg_duration_ms].to_i
    max_ms = finding[:max_duration_ms].to_i
    ratio  = finding[:avg_scan_ratio].to_f.round(0).to_i

    <<~BODY
      ## Performance Issue Detected by PerformanceIQ

      **Collection:** `#{finding[:collection]}` | **Avg query time:** #{avg_ms}ms | **Ops in 24h:** #{finding[:total_ops]}
      **Query hash:** #{finding[:query_hash]} | **Plan:** `#{finding[:plan_summary]}`

      ## Root Cause
      #{finding[:root_cause] || finding[:root_cause_type]}

      Avg scan ratio: **#{ratio}** (#{ratio} docs examined per doc returned).

      ## Suggested Fix

      Run in mongo shell against `factory_production`:

      ```javascript
      #{finding[:index_suggestion]}
      ```

      ## Before / After (estimated)

      | Metric | Before | After |
      |--------|--------|-------|
      | Avg query time | #{avg_ms}ms | ~#{(avg_ms / [ratio, 1].max).clamp(1, avg_ms)}ms |
      | Max query time | #{max_ms}ms | — |
      | Scan ratio | #{ratio} | ~1 |

      ---
      🤖 Auto-generated by PerformanceIQ — review before applying to production
    BODY
  end

  def fix_document(finding)
    "# Performance Fix — #{finding[:collection]}\n\n#{pr_body(finding)}"
  end
end
